#!/bin/bash

export GIT_PAGER="less $LESS -F -S"

GIT_PAGER="${GIT_PAGER/ -j[0-9] / }"
GIT_PAGER="${GIT_PAGER/ -j[0-9][0-9] / }"
GIT_PAGER="${GIT_PAGER/-a / }"

case "$GIT_PAGER_MODE" in
    log)
        git_pager_regexp='^commit [0-9a-f]{7}.*'
        ;;
    diff)
        git_pager_regexp='^diff .*'
        ;;
    commit)
        git_pager_regexp='^(commit [0-9a-f]{7}.*|diff .*)'
        ;;
    oneline)
        git_pager_regexp='^[0-9a-f]{7}[0-9a-f]*'
        ;;
    default|"")
        #git_pager_regexp='^(commit [0-9a-f]{7}.*|diff .*|[0-9a-f]{7}[0-9a-f]*)'
        unset git_pager_regexp
        ;;
    none)
        unset git_pager_regexp
        ;;
    *)
        echo "ERROR: unrecognised value for GIT_PAGER_MODE [$GIT_PAGER_MODE]" >&2
        ;;
esac

[ -n "$git_pager_regexp" ] && GIT_PAGER="$GIT_PAGER +/'$git_pager_regexp'"
