#!/bin/bash

export GIT_PAGER="less $LESS -F -S"

GIT_PAGER="${GIT_PAGER/ -j[0-9] / }"
GIT_PAGER="${GIT_PAGER/ -j[0-9][0-9] / }"
# GIT_PAGER="${GIT_PAGER/-a / }"

if which difft >&/dev/null; then
    export GIT_EXTERNAL_DIFF="difft --display inline"
elif which delta >&/dev/null; then
    export DELTA_PAGER="$GIT_PAGER"
    unset GIT_PAGER
    return
fi

git_diff_highlight=

case "$GIT_PAGER_MODE" in
    log)
        git_pager_regexp='^commit [0-9a-f]{7}.*'
        git_diff_highlight=y
        ;;
    diff)
        # ggsh could be showing a merge commit
        if [ "$GIT_EXTERNAL_DIFF" == difft ]; then
            git_pager_regexp=' --- [0-9]+/[0-9]+ ---'
        else
            git_pager_regexp='^(diff|commit) .*'
        fi
        git_diff_highlight=y
        ;;
    commit)
        git_pager_regexp='^(commit [0-9a-f]{7}.*|diff .*)'
        git_diff_highlight=y
        ;;
    oneline)
        # FIXME: what's the idea behind this?
        git_pager_regexp='^[0-9a-f]{7}[0-9a-f]*'
        ;;
    default|"")
        #git_pager_regexp='^(commit [0-9a-f]{7}.*|diff .*|[0-9a-f]{7}[0-9a-f]*)'
        unset git_pager_regexp
        ;;
    none)
        unset git_pager_regexp
        GIT_PAGER=""
        ;;
    *)
        echo "ERROR: unrecognised value for GIT_PAGER_MODE [$GIT_PAGER_MODE]" >&2
        ;;
esac

[ -n "$git_pager_regexp" ] && GIT_PAGER="$GIT_PAGER +/'$git_pager_regexp'"

if which diff-highlight >/dev/null 2>&1; then
    [ -n "$git_diff_highlight" ] && [ -n "$GIT_PAGER" ] && GIT_PAGER="diff-highlight | $GIT_PAGER"
fi
