#!/bin/bash

if ! which git >&/dev/null; then
    echo "git not found; aborting .cfg-post.d/git" >&2
    exit 1
fi

if which zsh >&/dev/null; then
  zsh -c zrec
fi

git config --global color.ui auto
git config --global color.pager true
git config --global color.diff auto

# Paging
#git config --global core.pager $PAGER
git config --global --bool pager.diff-tree true

git config --global --bool rebase.autosquash true

git config --global push.default >/dev/null || \
    git config --global push.default upstream

git config --global --bool merge.defaultToUpstream true
git config --global        core.attributesfile ~/.gitattributes
git config --global        core.excludesfile ~/.gitignore
git config --global        receive.denyCurrentBranch refuse
git config --global --bool rerere.enabled true

git config --global diff.lisp.xfuncname "^(\\(def.+)"
git config --global diff.sclang.xfuncname "^[[:space:]]*(\*?[[:alnum:]_]+ *\\{.*)"
git config --global diff.schelp.xfuncname \
    "^((TITLE|SUMMARY|DESCRIPTION|(SUB)?SECTION|(CLASS|INSTANCE)METHODS|PRIVATE|METHOD|EXAMPLES)::.*)"

# Work around port blocking at hotels etc.
# See file:git.org::*protocols
#
# This is not a good idea to do globally, because not all sites use the same
# path for both protocols.  For example:
#
#   https://libvirt.org/downloads.html#git
#
#git config --global url."https://".insteadOf git://

git config --global credential.helper 'cache --timeout=3600'
