#!/bin/sh

if which zsh >&/dev/null; then
  zsh -c zrec
fi

git config --global core.excludesfile ~/.gitignore

# too lazy to make separate cfgctl module with personal config
if [[ "$ZDOTUSER" == adam.spiers ]]; then
  git config --global user.name "Adam Spiers"
  # set user.email on a per-project basis
  git config --global user.signingkey 7A2F2DDC
fi

