#!/bin/bash

if ! which git >&/dev/null; then
    echo "git not found; aborting .cfg-post.d/git" >&2
    exit 1
fi

if which zsh >&/dev/null; then
  zsh -c zrec
fi

git config --global color.ui auto
git config --global color.pager true
git config --global color.diff auto

git config --global sendemail.confirm always

# Paging
#git config --global core.pager $PAGER
git config --global --bool pager.diff-tree true

git config --global --bool rebase.autosquash true
git config --global        pull.ff only

git config --global push.default >/dev/null || \
    git config --global push.default upstream
git config --global remote.pushDefault github

# tarsius recommends "always" as the sensible default, not "true":
# https://github.com/magit/magit/issues/4508#issuecomment-923177662
git config --global branch.autoSetupMerge always

git config --global --bool merge.defaultToUpstream true
git config --global        merge.conflictStyle diff3
git config --global        core.attributesfile ~/.gitattributes
git config --global        core.excludesfile ~/.gitignore
git config --global        receive.denyCurrentBranch updateInstead
git config --global --bool rerere.enabled true

git config --global diff.org.xfuncname "^\\*+ +(.*)$"
git config --global diff.lisp.xfuncname "^(\\(def.+)"
git config --global diff.sclang.xfuncname "^[[:space:]]*(\*?[[:alnum:]_]+ *\\{.*)"
git config --global diff.schelp.xfuncname \
    "^((TITLE|SUMMARY|DESCRIPTION|(SUB)?SECTION|(CLASS|INSTANCE)METHODS|PRIVATE|METHOD|EXAMPLES)::.*)"

# Work around port blocking at hotels etc.
# See file:git.org::*protocols
#
# This is not a good idea to do globally, because not all sites use the same
# path for both protocols.  For example:
#
#   https://libvirt.org/downloads.html#git
#
#git config --global url."https://".insteadOf git://

git config --global credential.helper 'cache --timeout=3600'

if which delta >&/dev/null; then
    # git config --global core.pager delta
    git config --global interactive.diffFilter 'delta --color-only'
    git config --global delta.light false
    git config --global delta.navigate true
    git config --global delta.side-by-side true
    git config --global delta.line-numbers true
    git config --global diff.colorMoved default
fi
